<!-- ============================================================
     PRATIK AMBASTHA · profile readme
     MODULAR — every block is marked. to update:
       · banner text ......... edit banner.svg
       · intro lines ......... edit TYPING block (lines= param)
       · projects ............ edit FEATURED PROJECTS table
       · skills .............. edit TECH STACK badges
       · snake graph ......... auto-generated by .github/workflows/snake.yml
     palette: parchment #c6bfa3 · ink #454138 · muted #6b6657 · accent #8a3033
     ============================================================ -->

<!-- ===== BANNER ===== -->
<p align="center">
  <img src="banner.svg" alt="Pratik Ambastha — Software Engineer" width="100%">
</p>

<!-- ===== TYPING INTRO ===== -->
<p align="center">
  <a href="https://amorfati3735.github.io/portfolio_v3/">
    <img src="https://readme-typing-svg.demolab.com?font=Share+Tech+Mono&size=20&pause=900&color=454138&center=true&vCenter=true&width=620&height=42&lines=Full-stack+developer+%C2%B7+web%2C+mobile+%26+terminal;React+%C2%B7+TypeScript+%C2%B7+Node+%C2%B7+Python+%C2%B7+Kotlin;Building+with+AI+agents+%26+systems+tooling;Open+to+SDE+%2F+placement+opportunities+%E2%80%94+2026" alt="intro">
  </a>
</p>

<br>

<!-- ===== ABOUT ===== -->
<p align="center">
  <code>[ ABOUT ]</code>
</p>

> Final-year CS student who ships end-to-end — from MongoDB-backed full-stack platforms
> to Android clients, data-viz tools, and Python automation. I like clean interfaces,
> fast feedback loops, and turning rough ideas into things that actually run in production.

<br>

<!-- ===== TECH STACK ===== -->
<p align="center">
  <code>[ STACK ]</code>
</p>

<p align="center">
  <img src="https://img.shields.io/badge/TypeScript-454138?style=flat-square&logo=typescript&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/JavaScript-454138?style=flat-square&logo=javascript&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Python-454138?style=flat-square&logo=python&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Kotlin-454138?style=flat-square&logo=kotlin&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/C-454138?style=flat-square&logo=c&logoColor=c6bfa3">
  <br>
  <img src="https://img.shields.io/badge/React-454138?style=flat-square&logo=react&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Node.js-454138?style=flat-square&logo=nodedotjs&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Express-454138?style=flat-square&logo=express&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/MongoDB-454138?style=flat-square&logo=mongodb&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Vite-454138?style=flat-square&logo=vite&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Framer_Motion-454138?style=flat-square&logo=framer&logoColor=c6bfa3">
  <br>
  <img src="https://img.shields.io/badge/Android-454138?style=flat-square&logo=android&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Linux-454138?style=flat-square&logo=linux&logoColor=c6bfa3">
  <img src="https://img.shields.io/badge/Git-454138?style=flat-square&logo=git&logoColor=c6bfa3">
</p>

<br>

<!-- ===== FEATURED PROJECTS  (edit rows freely) ===== -->
<p align="center">
  <code>[ FEATURED PROJECTS ]</code>
</p>

| Project | What it does | Stack | |
|---|---|---|---|
| **[UniArchive](https://github.com/amorfati3735/uniarch-agent)** | Full-stack academic resource-sharing platform — file uploads, auth, votes & comments, stats dashboards, AI moderation | React 19 · Express · MongoDB · Cloudinary · JWT | [live](https://uniarch.vercel.app) |
| **[Algorithm Visualizer](https://github.com/amorfati3735/algorithm-visualizer)** | Trace-based sort/search visualizer with scrub, step-back, speed control & live code-line highlighting | React 19 · TypeScript · Framer Motion | [live](https://algo-vis-v2.vercel.app) |
| **[Terminal Quizzer](https://github.com/amorfati3735/terminal-quizzer)** | Keyboard-first active-recall MCQ platform with a robust regex parser & wrong-answer export | React 19 · TypeScript · Vite | [live](https://terminal-quizzer.vercel.app) |
| **[GPS Tracker](https://github.com/amorfati3735/gps-tracker)** | Real-time ESP32 GPS tracker streaming over the Web Serial API onto an interactive map | JS · Web Serial · Leaflet | [live](https://gps-tracker-ashen-two.vercel.app) |
| **[dev.blog](https://github.com/amorfati3735/blog)** | Markdown-driven digital garden with file-tree UI, command palette, live editor & syntax highlighting | React 19 · TypeScript · PrismJS | [live](https://ptk-dev.vercel.app) |
| **[Finances Analyzer](https://github.com/amorfati3735/finances-analyzer)** | CLI that extracts transactions from PDF statements & generates a reconciled spending report | Python · PyMuPDF · regex | — |

<br>

<!-- ===== STATS ===== -->
<p align="center">
  <code>[ TELEMETRY ]</code>
</p>

<p align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=amorfati3735&show_icons=true&hide_rank=true&bg_color=c6bfa3&title_color=454138&text_color=4e4b42&icon_color=5f5b50&border_color=4e4b42" height="165">
  <img src="https://github-readme-streak-stats.herokuapp.com/?user=amorfati3735&background=c6bfa3&border=4e4b42&stroke=4e4b42&ring=454138&fire=8a3033&currStreakNum=454138&sideNums=4e4b42&currStreakLabel=454138&sideLabels=5f5b50&dates=6b6657" height="165">
</p>

<p align="center">
  <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=amorfati3735&layout=compact&langs_count=8&bg_color=c6bfa3&title_color=454138&text_color=4e4b42&border_color=4e4b42" height="160">
</p>

<br>

<!-- ===== CONTRIBUTION SNAKE  (auto-generated, see workflows/snake.yml) ===== -->
<p align="center">
  <code>[ ACTIVITY ]</code>
</p>

<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/amorfati3735/amorfati3735/output/github-snake-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/amorfati3735/amorfati3735/output/github-snake.svg">
    <img alt="contribution snake" src="https://raw.githubusercontent.com/amorfati3735/amorfati3735/output/github-snake.svg">
  </picture>
</p>

<br>

<!-- ===== CONNECT ===== -->
<p align="center">
  <code>[ CONNECT ]</code>
</p>

<p align="center">
  <a href="https://amorfati3735.github.io/portfolio_v3/"><img src="https://img.shields.io/badge/Portfolio-454138?style=flat-square&logo=vercel&logoColor=c6bfa3"></a>
  <a href="https://github.com/amorfati3735"><img src="https://img.shields.io/badge/GitHub-454138?style=flat-square&logo=github&logoColor=c6bfa3"></a>
  <a href="mailto:pratikambastha5@gmail.com"><img src="https://img.shields.io/badge/Email-454138?style=flat-square&logo=gmail&logoColor=c6bfa3"></a>
  <a href="https://www.linkedin.com/in/pratik-ambastha-610b8a416/"><img src="https://img.shields.io/badge/LinkedIn-454138?style=flat-square&logo=linkedin&logoColor=c6bfa3"></a>
</p>
